// src/utils/ledger-pdf.ts
// Generates a PDF file from ledger JSON returned by the generate-ledger Edge Function.
// Uses jsPDF + jspdf-autotable.

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'
import type { LedgerData } from './ledger-excel'

const BRAND_BLUE = '#4A6CF7'
const BRAND_DARK = '#1A1D2E'
const MUTED = '#6B7280'
const GREEN = '#16A34A'
const RED = '#DC2626'
const ORANGE = '#D97706'
const LIGHT_GRAY = '#F3F4F6'

const RUPEE = 'Rs.'

function inr(amount: number): string {
  if (amount >= 10000000) return `${RUPEE}${Math.round(amount / 10000000)}Cr`
  if (amount >= 100000) return `${RUPEE}${Math.round(amount / 100000)}L`
  if (amount >= 1000) return `${RUPEE}${Math.round(amount / 1000)}K`
  return `${RUPEE}${amount.toLocaleString('en-IN')}`
}

function shortId(id: string): string {
  return id.slice(0, 8).toUpperCase()
}

function fmtDate(ts: number | null): string {
  if (!ts) return ''
  return format(ts, 'dd MMM yyyy')
}

function stateColor(state: string): [number, number, number] {
  switch (state.toLowerCase()) {
    case 'delivered': return [22, 163, 74]
    case 'placed':
    case 'accepted': return [74, 108, 247]
    case 'dispatched': return [217, 119, 6]
    default: return [107, 114, 128]
  }
}

function addFooter(doc: jsPDF, date: string): void {
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(MUTED)
    doc.text(
      `Generated by Zelto · zeltoapp.com · ${date}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' }
    )
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      pageHeight - 8,
      { align: 'right' }
    )
  }
}

export function generateLedgerPdf(data: LedgerData): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 14
  let y = margin

  // ── Header ─────────────────────────────────────────────────────────────
  doc.setFontSize(22)
  doc.setTextColor(BRAND_BLUE)
  doc.setFont('helvetica', 'bold')
  doc.text('ZELTO', margin, y + 6)

  doc.setFontSize(14)
  doc.setTextColor(BRAND_DARK)
  doc.text(`Ledger Report — ${data.meta.period}`, margin + 24, y + 6)

  doc.setFontSize(9)
  doc.setTextColor(MUTED)
  doc.setFont('helvetica', 'normal')
  const genDate = fmtDate(data.meta.generatedAt)
  doc.text(`Generated: ${genDate}`, pageWidth - margin, y + 6, { align: 'right' })

  y += 14

  // ── Business info boxes ─────────────────────────────────────────────────
  const boxW = (data.meta.scope === 'single' && data.meta.otherBusiness) ? (pageWidth - margin * 2 - 6) / 2 : pageWidth - margin * 2
  const boxH = 28

  // My business box
  doc.setFillColor(LIGHT_GRAY)
  doc.roundedRect(margin, y, boxW, boxH, 3, 3, 'F')
  doc.setFontSize(8)
  doc.setTextColor(MUTED)
  doc.setFont('helvetica', 'bold')
  doc.text('MY BUSINESS', margin + 4, y + 6)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(BRAND_DARK)
  doc.text(data.meta.myBusiness.name, margin + 4, y + 12)
  doc.setFontSize(8)
  doc.setTextColor(MUTED)
  doc.text(`Code: ${data.meta.myBusiness.zeltoCode}`, margin + 4, y + 18)
  if (data.meta.myBusiness.phone) doc.text(`Ph: ${data.meta.myBusiness.phone}`, margin + 4, y + 23)
  const cityLine = [data.meta.myBusiness.city, data.meta.myBusiness.area].filter(Boolean).join(', ')
  if (cityLine) doc.text(cityLine, margin + boxW / 2, y + 23)

  // Other business box (single scope only)
  if (data.meta.scope === 'single' && data.meta.otherBusiness) {
    const otherX = margin + boxW + 6
    doc.setFillColor(LIGHT_GRAY)
    doc.roundedRect(otherX, y, boxW, boxH, 3, 3, 'F')
    doc.setFontSize(8)
    doc.setTextColor(MUTED)
    doc.setFont('helvetica', 'bold')
    doc.text('THEIR BUSINESS', otherX + 4, y + 6)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(BRAND_DARK)
    doc.text(data.meta.otherBusiness.name, otherX + 4, y + 12)
    doc.setFontSize(8)
    doc.setTextColor(MUTED)
    doc.text(`Code: ${data.meta.otherBusiness.zeltoCode}`, otherX + 4, y + 18)
    if (data.meta.otherBusiness.phone) doc.text(`Ph: ${data.meta.otherBusiness.phone}`, otherX + 4, y + 23)
    const otherCityLine = [data.meta.otherBusiness.city, data.meta.otherBusiness.area].filter(Boolean).join(', ')
    if (otherCityLine) doc.text(otherCityLine, otherX + boxW / 2, y + 23)
  }

  y += boxH + 8

  // ── Summary stats row ───────────────────────────────────────────────────
  const stats = [
    { label: 'Total Orders', value: String(data.summary.totalOrders), color: BRAND_BLUE },
    { label: 'Total Value', value: inr(data.summary.totalOrderValue), color: BRAND_DARK },
    { label: 'Paid', value: inr(data.summary.totalPaid), color: GREEN },
    { label: 'Outstanding', value: inr(data.summary.totalOutstanding), color: RED },
    { label: 'Issues', value: String(data.summary.issueCount), color: ORANGE },
  ]

  const statW = (pageWidth - margin * 2 - (stats.length - 1) * 3) / stats.length
  const statH = 18

  stats.forEach((stat, i) => {
    const sx = margin + i * (statW + 3)
    doc.setFillColor(LIGHT_GRAY)
    doc.roundedRect(sx, y, statW, statH, 2, 2, 'F')
    doc.setFontSize(7)
    doc.setTextColor(MUTED)
    doc.setFont('helvetica', 'normal')
    doc.text(stat.label, sx + statW / 2, y + 5, { align: 'center' })
    doc.setFontSize(10)
    doc.setTextColor(stat.color)
    doc.setFont('helvetica', 'bold')
    doc.text(stat.value, sx + statW / 2, y + 13, { align: 'center' })
  })

  y += statH + 8

  // ── Orders table ────────────────────────────────────────────────────────
  const orderRows: any[][] = []
  for (const conn of data.connections) {
    for (const order of conn.orders) {
      orderRows.push([
        fmtDate(order.placedAt),
        conn.otherBusiness.name,
        conn.myRole,
        order.itemSummary,
        inr(order.orderValue),
        { content: order.state, styles: { textColor: stateColor(order.state) } },
        inr(order.totalPaid),
        {
          content: inr(order.balance),
          styles: {
            textColor: order.balance > 0 && order.dueDate && Date.now() > order.dueDate
              ? [220, 38, 38]
              : order.balance === 0
                ? [22, 163, 74]
                : [26, 29, 46],
          },
        },
      ])
    }
  }

  if (orderRows.length > 0) {
    doc.setFontSize(11)
    doc.setTextColor(BRAND_DARK)
    doc.setFont('helvetica', 'bold')
    doc.text('Orders', margin, y)
    y += 4

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Connection', 'Role', 'Items', 'Value', 'Status', 'Paid', 'Balance']],
      body: orderRows,
      styles: { fontSize: 8, cellPadding: { top: 2, right: 3, bottom: 2, left: 3 }, overflow: 'ellipsize' },
      headStyles: { fillColor: [26, 26, 46] as [number, number, number], textColor: 255, fontSize: 8, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 24 },
        1: { cellWidth: 44 },
        2: { cellWidth: 18 },
        3: { cellWidth: 70 },
        4: { cellWidth: 24 },
        5: { cellWidth: 24 },
        6: { cellWidth: 24 },
        7: { cellWidth: 24 },
      },
      margin: { left: margin, right: margin },
      didDrawPage: () => {},
    })

    y = (doc as any).lastAutoTable.finalY + 8
  }

  // ── Payments table ──────────────────────────────────────────────────────
  const paymentRows: any[][] = []
  for (const conn of data.connections) {
    for (const order of conn.orders) {
      for (const payment of order.payments) {
        paymentRows.push([
          shortId(order.id),
          conn.otherBusiness.name,
          fmtDate(payment.date),
          inr(payment.amount),
          payment.note,
        ])
      }
    }
  }

  if (paymentRows.length > 0) {
    doc.setFontSize(11)
    doc.setTextColor(BRAND_DARK)
    doc.setFont('helvetica', 'bold')
    doc.text('Payments', margin, y)
    y += 4

    autoTable(doc, {
      startY: y,
      head: [['Order ID', 'Connection', 'Date', 'Amount (₹)', 'Note']],
      body: paymentRows,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: BRAND_BLUE, textColor: '#FFFFFF', fontStyle: 'bold' },
      margin: { left: margin, right: margin },
    })

    y = (doc as any).lastAutoTable.finalY + 8
  }

  // ── Issues table ────────────────────────────────────────────────────────
  const issueRows: any[][] = []
  for (const conn of data.connections) {
    for (const order of conn.orders) {
      for (const issue of order.issues) {
        issueRows.push([
          shortId(order.id),
          conn.otherBusiness.name,
          issue.type,
          issue.severity,
          issue.raisedBy,
          issue.status,
          issue.description,
          fmtDate(issue.resolvedAt),
        ])
      }
    }
  }

  if (issueRows.length > 0) {
    doc.setFontSize(11)
    doc.setTextColor(BRAND_DARK)
    doc.setFont('helvetica', 'bold')
    doc.text('Issues', margin, y)
    y += 4

    autoTable(doc, {
      startY: y,
      head: [['Order ID', 'Connection', 'Type', 'Severity', 'Raised By', 'Status', 'Description', 'Resolved']],
      body: issueRows,
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [220, 38, 38] as [number, number, number], textColor: '#FFFFFF', fontStyle: 'bold' },
      margin: { left: margin, right: margin },
    })
  }

  // ── Footer on every page ────────────────────────────────────────────────
  addFooter(doc, genDate)

  // ── Save ────────────────────────────────────────────────────────────────
  const dateStr = format(data.meta.generatedAt, 'yyyyMMdd')
  const periodSlug = data.meta.period.toLowerCase().replace(/\s+/g, '-')
  doc.save(`zelto-ledger-${periodSlug}-${dateStr}.pdf`)
}
